mv PbPbV2_Ch.pdf                    /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Fluct_Ch.pdf              /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Fluct_Ks.pdf              /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Fluct_Lm.pdf              /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Ks.pdf                    /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Lm.pdf                    /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_SubevtCu_Ratio.pdf        /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Subevt_Ch.pdf             /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Subevt_Ks.pdf             /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Subevt_Lm.pdf             /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_V64_ratio.pdf             /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_V84_ratio.pdf             /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Ks.pdf                     /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Lm.pdf                     /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Subevt_Ch.pdf              /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Subevt_Ks.pdf              /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Subevt_Lm.pdf              /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_ch.pdf                     /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Ch_veto.pdf                /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Ch_vetoRatio.pdf           /Users/qwang/github/tdr/HIN-19-004/figures/
mv pPbV2_Ratio_Ch.pdf               /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Ch42.pdf                  /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Ks42.pdf                  /Users/qwang/github/tdr/HIN-19-004/figures/
mv PbPbV2_Lm42.pdf                  /Users/qwang/github/tdr/HIN-19-004/figures/
